package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'KotlinSetBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("KotlinSetBuild")) {
    params {
        add {
            param("system.commit.status.publisher.username", "kse19202")
        }
        add {
            password("system.commit.status.publisher.password", "credentialsJSON:c10d4c4c-7993-4766-8d90-47cfe53543cd")
        }
    }

    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "KotlinSet_ShortBranches3_HttpsKse19202bitbucketOrgKse19202kotlinBbGit"
                publisher = bitbucketCloud {
                    userName = "%system.commit.status.publisher.username%"
                    password = "%system.commit.status.publisher.password%"
                }
            }
        }
        feature1.apply {
            publisher = bitbucketCloud {
                userName = "%system.commit.status.publisher.username%"
                password = "credentialsJSON:68940d9f-fade-4ea9-8d11-edf4247611a4"
            }
        }
    }
}
