package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("system.bitbuck.username", "admin")
        }
        add {
            password("system.bitbuck.password", "credentialsJSON:d36b965b-5b1c-4e1e-970d-f3b681f6ad39")
        }
    }
}
